### ISSUE TITLE
Branch prefix not working

### ISSUE THREAD

**Issue by raanglada** [lablnet/create-branch-from-tag#4]
Hi lablnet,

I tested the latest version and the branch prefix is not working:

Here is my code:

`      - name: "test release branch"
        uses: lablnet/create-branch-from-tag@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch_prefix: 'release/'
          tag_name: "testag"
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
`

Regards

**Comment by lablnet** [comment]
Can you please clarify and provide me with your complete workflow code.

as per in the document you should specify on which tag you want to listen.

```yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
 ```
